### ISSUE TITLE
Sell Drugs to Peds

### ISSUE THREAD

**Issue by Psycholiquid71** [JiminyKroket/esx_jk_drugs#4]
What are the chances of you adding being able to sell drugs to peds. I cant seem to get any of the existing mods to allow it with these drugs. Seem they want drug pooches in order to work.

**Comment by CanadianSyrup** [comment]
That would be pretty awesome if you did.

**Comment by nertigel** [comment]
https://github.com/ESX-PUBLIC/esx_npcdrugsales
https://github.com/BTNGaming/esx_sell
https://github.com/StasiekESX/stasiek_selldrugs

Just implement the new drugs to one of those, should take you barely 5 minutes.
I don't see any point in having some useless sell drug script inside of the main esx_drugs.

**Comment by Psycholiquid71** [comment]
Not a coder, was asking to see if it could be done not for some off hand comment of  "I am better than you"

**Comment by JiminyKroket** [comment]
Unfortunately Psycho I do not feel comfortable with my ability to write an NPC sell script at this current time. Most of them are super resource heavy on the client as they collect all peds immediately one after another so I will not integrate one of them into the current script. It might be added way later but before I attempt to add a new sell option I would like to finish the script and get it functioning fully. I've been informed the script currently is not friendly to users above ~20 so I am currently working on shortening the code and removing server stress. I will mark this post as an "idea" but I will close it as it is not an issue regarding my code. As nertigel mentioned there are multiple NPC sell scripts out there with Config options to add new items. As long as you add the items properly with the DB name the NPC scripts should work fine with any, actually any item at all.
