### ISSUE TITLE
Coordinates.

### ISSUE THREAD

**Issue by vicciusomerta** [JiminyKroket/esx_jk_drugs#5]
I tried to change coordinates zone height for some locations and i see the blip and the marker but it doens't work. How can i change the coordinates and make them work ?

**Comment by Dynorez** [comment]
same thing happen to me

**Comment by JiminyKroket** [comment]
What coordinates are you changing specifically? Also have you checked your f8 and server console for errors?

**Comment by JiminyKroket** [comment]
Adjusted GetCoordZ function in the latest release, which can be found here https://github.com/JiminyKroket/esx_jk_drugs/releases/tag/1.1 or from redownloading the latest version from the main github page here https://github.com/JiminyKroket/esx_jk_drugs. Please be sure to follow all directions when updating to the latest version, thank you.
