### ISSUE TITLE
resource time warning, since getting the latest update

### ISSUE THREAD

**Issue by haarperr** [JiminyKroket/esx_jk_drugs#6]
https://imgur.com/xJNBsF3
https://imgur.com/pSVYPAQ

**Comment by JiminyKroket** [comment]
This is being looked into. Thank you for your feedback and I will make sure to keep you posted.

**Comment by JiminyKroket** [comment]
Thank you so much for you information on it being since the latest update. Please download the latest client/main.lua or simply remove the police kits from the bottom of your current copy.
