### ISSUE TITLE
high tick

### ISSUE THREAD

**Issue by Tim885885** [JiminyKroket/esx_jk_drugs#7]
on 128 slots server.
![Pic](https://i.imgur.com/ZDb2U39.png)

**Comment by JiminyKroket** [comment]
Have you download the latest version?

**Comment by Tim885885** [comment]
> 
> 
> Have you download the latest version?

yes

**Comment by JiminyKroket** [comment]
If i could ask how you are viewing these ticks, so i may attempt to find the issue, that would be appreciated.

**Comment by Tim885885** [comment]
[here](https://forum.fivem.net/t/speeding-up-your-server-101-windows/176205)

**Comment by haarperr** [comment]
why the name is esx_drugs?

**Comment by JiminyKroket** [comment]
I assumed... He renamed the file. Idk why he would have but I also assume even if esx_drugs has this issue mine would too anyway. Just never seen a "tick" check yet

**Comment by JiminyKroket** [comment]
Also did you attempt this "Anything over 50ms should be reported to the threads of the respective resources, or posted as issues on github with a description how the hitch happened, e.g. full server.

If you are okay enough with scripting you can try and find out which part of the code hangs yourself in that resource. If you do, do not forget to inform the people in the resource’s topic on the FiveM forums or on github, or on both."

**Comment by JiminyKroket** [comment]
Testing myself the highest tick I received was 7.21, I believe which was on load as peds spawn, but not 100% on that, and below that the next highest es_jk_drugs tick was .36. Unless there's more information you can give me, I'm gonna have to say it's a 128 slot issue.

**Comment by JiminyKroket** [comment]
Closing due to failed response, as well as lack of information.
